package weather2.integration;

/**
 * NTNH Deep Module: Diagnostic report generated by an integration adapter.
 */
public class AdapterReport {

    private final String adapterName;
    private final String targetModId;
    private final AdapterStatus status;
    private final String details;
    private final boolean fallbackActive;
    private final String fallbackDescription;

    public AdapterReport(String adapterName, String targetModId, AdapterStatus status, String details,
        boolean fallbackActive, String fallbackDescription) {
        this.adapterName = adapterName != null ? adapterName : "UnknownAdapter";
        this.targetModId = targetModId != null ? targetModId : "unknown";
        this.status = status != null ? status : AdapterStatus.NOT_INSTALLED;
        this.details = details != null ? details : "";
        this.fallbackActive = fallbackActive;
        this.fallbackDescription = fallbackDescription != null ? fallbackDescription : "none";
    }

    public static AdapterReport notInstalled(String adapterName, String targetModId) {
        return new AdapterReport(
            adapterName,
            targetModId,
            AdapterStatus.NOT_INSTALLED,
            "Target mod not present in modpack",
            false,
            null);
    }

    public static AdapterReport active(String adapterName, String targetModId, String details) {
        return new AdapterReport(adapterName, targetModId, AdapterStatus.ACTIVE, details, false, null);
    }

    public static AdapterReport degraded(String adapterName, String targetModId, String reason,
        String fallbackDescription) {
        return new AdapterReport(adapterName, targetModId, AdapterStatus.DEGRADED, reason, true, fallbackDescription);
    }

    public static AdapterReport failed(String adapterName, String targetModId, String reason) {
        return new AdapterReport(
            adapterName,
            targetModId,
            AdapterStatus.FAILED,
            reason,
            false,
            "Adapter disabled via circuit breaker");
    }

    public static AdapterReport clientOnly(String adapterName, String targetModId) {
        return new AdapterReport(
            adapterName,
            targetModId,
            AdapterStatus.CLIENT_ONLY,
            "Client-side adapter bypassed on Dedicated Server",
            false,
            null);
    }

    public String getAdapterName() {
        return adapterName;
    }

    public String getTargetModId() {
        return targetModId;
    }

    public AdapterStatus getStatus() {
        return status;
    }

    public String getDetails() {
        return details;
    }

    public boolean isFallbackActive() {
        return fallbackActive;
    }

    public String getFallbackDescription() {
        return fallbackDescription;
    }

    @Override
    public String toString() {
        if (status == AdapterStatus.NOT_INSTALLED) {
            return String.format("%-24s [%s] - Not present", adapterName, targetModId);
        } else if (status == AdapterStatus.CLIENT_ONLY) {
            return String.format("%-24s [%s] - CLIENT_ONLY: %s", adapterName, targetModId, details);
        } else if (status == AdapterStatus.ACTIVE) {
            return String.format("%-24s [%s] - ACTIVE: %s", adapterName, targetModId, details);
        } else if (status == AdapterStatus.DEGRADED) {
            return String.format(
                "%-24s [%s] - DEGRADED: %s (Fallback: %s)",
                adapterName,
                targetModId,
                details,
                fallbackDescription);
        } else {
            return String.format("%-24s [%s] - FAILED: %s", adapterName, targetModId, details);
        }
    }
}
