package weather2.client.block;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

import org.lwjgl.opengl.GL11;

public class ModelWindVane extends ModelBase {

    ModelRenderer bottom;
    ModelRenderer cross;
    ModelRenderer cross2;
    ModelRenderer N;
    ModelRenderer S;
    ModelRenderer E;
    ModelRenderer W;
    ModelRenderer Block2;
    ModelRenderer Block3;
    ModelRenderer top1;
    ModelRenderer chicken;
    ModelRenderer Block4;
    ModelRenderer Block5;
    ModelRenderer arrow;
    ModelRenderer point;
    ModelRenderer feather;
    public float scaleX;
    public float scaleY;
    public float scaleZ;
    public float scaleItem;
    public float offsetX;
    public float offsetY;
    public float offsetZ;
    public float offsetInvX;
    public float offsetInvY;

    public ModelWindVane() {
        this(0.0F);
    }

    public ModelWindVane(float par1) {
        this.scaleX = 1.0F;
        this.scaleY = 1.0F;
        this.scaleZ = 1.0F;
        this.scaleItem = 1.0F;
        this.offsetX = 0.0F;
        this.offsetY = 0.0F;
        this.offsetZ = 0.0F;
        this.offsetInvX = 0.0F;
        this.offsetInvY = 0.0F;
        this.bottom = new ModelRenderer(this, 0, 0);
        this.bottom.setTextureSize(64, 32);
        this.bottom.addBox(-0.5F, -8.0F, -0.5F, 1, 16, 1);
        this.bottom.setRotationPoint(0.0F, 16.0F, 0.0F);
        this.cross = new ModelRenderer(this, 7, 3);
        this.cross.setTextureSize(64, 32);
        this.cross.addBox(-0.5F, -0.5F, -5.0F, 1, 1, 10);
        this.cross.setRotationPoint(0.0F, 9.500001F, 0.0F);
        this.cross2 = new ModelRenderer(this, 7, 3);
        this.cross2.setTextureSize(64, 32);
        this.cross2.addBox(-0.5F, -0.5F, -5.0F, 1, 1, 10);
        this.cross2.setRotationPoint(0.0F, 9.500001F, 0.0F);
        this.N = new ModelRenderer(this, 21, 0);
        this.N.setTextureSize(64, 32);
        this.N.addBox(0.0F, -1.5F, -1.5F, 0, 3, 3);
        this.N.setRotationPoint(-2.107342E-7F, 9.500001F, 6.5F);
        this.S = new ModelRenderer(this, 27, 0);
        this.S.setTextureSize(64, 32);
        this.S.addBox(0.0F, -1.5F, -1.5F, 0, 3, 3);
        this.S.setRotationPoint(1.421085E-14F, 9.5F, -6.5F);
        this.E = new ModelRenderer(this, 33, 0);
        this.E.setTextureSize(64, 32);
        this.E.addBox(0.0F, -1.5F, -1.5F, 0, 3, 3);
        this.E.setRotationPoint(6.5F, 9.5F, -4.768372E-7F);
        this.W = new ModelRenderer(this, 39, 0);
        this.W.setTextureSize(64, 32);
        this.W.addBox(0.0F, -1.5F, -1.5F, 0, 3, 3);
        this.W.setRotationPoint(-6.5F, 9.5F, -4.768372E-7F);
        this.Block2 = new ModelRenderer(this, 6, 0);
        this.Block2.setTextureSize(64, 32);
        this.Block2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.Block2.setRotationPoint(0.0F, 11.0F, 0.0F);
        this.Block3 = new ModelRenderer(this, 6, 0);
        this.Block3.setTextureSize(64, 32);
        this.Block3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.Block3.setRotationPoint(0.0F, 11.0F, 0.0F);
        this.top1 = new ModelRenderer(this, 0, 0);
        this.top1.setTextureSize(64, 32);
        this.top1.addBox(-0.5F, -3.0F, -0.5F, 1, 6, 1);
        this.top1.setRotationPoint(0.0F, 5.0F, 0.0F);
        this.chicken = new ModelRenderer(this, 5, 19);
        this.chicken.setTextureSize(64, 32);
        this.chicken.addBox(-5.0F, -5.0F, 0.0F, 10, 10, 0);
        this.chicken.setRotationPoint(0.0F, -3.0F, 0.0F);
        this.Block4 = new ModelRenderer(this, 6, 0);
        this.Block4.setTextureSize(64, 32);
        this.Block4.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.Block4.setRotationPoint(0.0F, 6.0F, 0.0F);
        this.Block5 = new ModelRenderer(this, 6, 0);
        this.Block5.setTextureSize(64, 32);
        this.Block5.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
        this.Block5.setRotationPoint(0.0F, 6.0F, 0.0F);
        this.arrow = new ModelRenderer(this, 25, 16);
        this.arrow.setTextureSize(64, 32);
        this.arrow.addBox(-5.0F, -0.5F, -0.5F, 10, 1, 1);
        this.arrow.setRotationPoint(0.0F, 3.0F, 0.0F);
        this.point = new ModelRenderer(this, 31, 8);
        this.point.setTextureSize(64, 32);
        this.point.addBox(0.0F, -1.5F, -1.5F, 0, 3, 3);
        this.point.setRotationPoint(-6.5F, 3.0F, 0.0F);
        this.feather = new ModelRenderer(this, 37, 8);
        this.feather.setTextureSize(64, 32);
        this.feather.addBox(0.0F, -1.5F, -1.5F, 0, 3, 3);
        this.feather.setRotationPoint(6.5F, 3.0F, 0.0F);
    }

    public void render(float scale, float topPieceRotation) {
        GL11.glRotatef(180.0F, 0.0F, 1.0F, 0.0F);
        this.bottom.rotateAngleX = 0.0F;
        this.bottom.rotateAngleY = 0.0F;
        this.bottom.rotateAngleZ = 0.0F;
        this.bottom.renderWithRotation(scale);
        this.cross.rotateAngleX = 0.0F;
        this.cross.rotateAngleY = 0.0F;
        this.cross.rotateAngleZ = 0.0F;
        this.cross.renderWithRotation(scale);
        this.cross2.rotateAngleX = 0.0F;
        this.cross2.rotateAngleY = -1.570796F;
        this.cross2.rotateAngleZ = 0.0F;
        this.cross2.renderWithRotation(scale);
        this.N.rotateAngleX = 0.0F;
        this.N.rotateAngleY = 0.0F;
        this.N.rotateAngleZ = 0.0F;
        this.N.renderWithRotation(scale);
        this.S.rotateAngleX = 0.0F;
        this.S.rotateAngleY = 4.561942E-8F;
        this.S.rotateAngleZ = 0.0F;
        this.S.renderWithRotation(scale);
        this.E.rotateAngleX = 0.0F;
        this.E.rotateAngleY = -1.570796F;
        this.E.rotateAngleZ = 0.0F;
        this.E.renderWithRotation(scale);
        this.W.rotateAngleX = 0.0F;
        this.W.rotateAngleY = -1.570796F;
        this.W.rotateAngleZ = 0.0F;
        this.W.renderWithRotation(scale);
        GL11.glRotatef(-180.0F, 0.0F, 1.0F, 0.0F);
        this.Block2.rotateAngleX = 0.0F;
        this.Block2.rotateAngleY = -0.7853982F;
        this.Block2.rotateAngleZ = 0.0F;
        this.Block2.renderWithRotation(scale);
        this.Block3.rotateAngleX = -9.134193E-9F;
        this.Block3.rotateAngleY = -3.362374E-8F;
        this.Block3.rotateAngleZ = -0.7853982F;
        this.Block3.renderWithRotation(scale);
        GL11.glRotatef(topPieceRotation, 0.0F, 1.0F, 0.0F);
        this.top1.rotateAngleX = 0.0F;
        this.top1.rotateAngleY = 0.0F;
        this.top1.rotateAngleZ = 0.0F;
        this.top1.renderWithRotation(scale);
        this.chicken.rotateAngleX = 0.0F;
        this.chicken.rotateAngleY = 0.0F;
        this.chicken.rotateAngleZ = 0.0F;
        this.chicken.renderWithRotation(scale);
        this.Block4.rotateAngleX = 0.0F;
        this.Block4.rotateAngleY = -0.7853982F;
        this.Block4.rotateAngleZ = 0.0F;
        this.Block4.renderWithRotation(scale);
        this.Block5.rotateAngleX = -9.134193E-9F;
        this.Block5.rotateAngleY = -3.362374E-8F;
        this.Block5.rotateAngleZ = -0.7853982F;
        this.Block5.renderWithRotation(scale);
        this.arrow.rotateAngleX = 0.0F;
        this.arrow.rotateAngleY = 0.0F;
        this.arrow.rotateAngleZ = 0.0F;
        this.arrow.renderWithRotation(scale);
        this.point.rotateAngleX = 0.0F;
        this.point.rotateAngleY = -1.570796F;
        this.point.rotateAngleZ = 0.0F;
        this.point.renderWithRotation(scale);
        this.feather.rotateAngleX = 0.0F;
        this.feather.rotateAngleY = -1.570796F;
        this.feather.rotateAngleZ = 0.0F;
        this.feather.renderWithRotation(scale);
    }
}
